---
- name: Backup important command output and reboot servers
  hosts: all
  become: true
  gather_facts: true

  vars:
    backup_commands:
      - { name: "uptime", cmd: "uptime" }
      - { name: "disk_usage", cmd: "df -h" }
      - { name: "memory", cmd: "free -m" }
      - { name: "last_logins", cmd: "last -n 10" }
      - { name: "running_processes", cmd: "ps aux --sort=-%mem | head -n 10" }
    backup_dir: "/tmp/pre_reboot_backups"

  tasks:
    - name: Create remote backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Run and save important command outputs
      shell: "{{ item.cmd }} > {{ backup_dir }}/{{ item.name }}.txt"
      loop: "{{ backup_commands }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Fetch backup files to local machine
      fetch:
        src: "{{ backup_dir }}/{{ item.name }}.txt"
        dest: "./backups/{{ inventory_hostname }}/"
        flat: yes
      loop: "{{ backup_commands }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by Ansible after backup"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 5
        post_reboot_delay: 30
        test_command: whoami

    - name: Wait for server to become reachable
      wait_for_connection:
        timeout: 300

