---
- name: Add fstab entry for new mount point
  hosts: all
  become: true
  tasks:
    - name: Ensure mount point directory exists
      file:
        path: /mnt
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Add fstab entry for /mnt
      lineinfile:
        path: /etc/fstab
        line: "/dev/sr0  /mnt  iso9660  loop,rw    0 0"
        state: present
        insertafter: EOF
        create: yes
        backup: yes

    - name: Mount the filesystem
      mount:
        path: /mnt
        src: /dev/sr0
        fstype: iso9660
        state: mounted
        opts: rw,loop
