---
- name: Add fstab entry for new mount point
  hosts: all
  become: true
  tasks:
    - name: Ensure mount point directory exists
      file:
        path: /mnt/data
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Add fstab entry for /mnt/data
      lineinfile:
        path: /etc/fstab
        line: "/dev/sdb1  /mnt/data  ext4  defaults  0  2"
        state: present
        insertafter: EOF
        create: yes
        backup: yes

    - name: Mount the filesystem
      mount:
        path: /mnt/data
        src: /dev/sdb1
        fstype: ext4
        opts: defaults
        state: mounted

