---
- name: Patch Linux server and reboot if needed
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update all packages (RHEL/CentOS/AlmaLinux/Rocky)
      dnf:
        name: '*'
        state: latest
      register: update_result
      when: ansible_facts['os_family'] == "RedHat"

    - name: Check if a reboot is required (RHEL-based)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required by update or detected by file
      reboot:
        msg: "Reboot initiated by Ansible after patching"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 10
        post_reboot_delay: 30
        test_command: whoami
      when: update_result is changed or reboot_required_file.stat.exists

    - name: Confirm system is back online
      wait_for_connection:
        timeout: 300

